### ISSUE TITLE
hostapd disconnecting clients

### ISSUE THREAD

**Issue by jcfigueiredo** [pritambaral/hostapd-rtl871xdrv#11]
Hi @all,

first thanks for the amazing work. This patch was the only thing that made my hostapd work with my usb dongle.

Just a question, out of curiosity. Has anyone been having problems with devices being disconnect every once in a while? Not sure it's just with me.

Thanks,

**Comment by ech0s7r** [comment]
Wich version of hostapd are you using ?

**Comment by jcfigueiredo** [comment]
hostapd 2.5. Thanks for asking!

**Comment by Waszker** [comment]
@jcfigueiredo  I can confirm the issue.

**Comment by pritambaral** [comment]
Closing due to irrelevance and inactivity.
