### ISSUE TITLE
Multiple SSID Support

### ISSUE THREAD

**Issue by jgornick** [pritambaral/hostapd-rtl871xdrv#13]
USB Wifi Dongle: TRENDnet TEW-648UBM (RTL8188CUS)
OS: Raspbian 4.1 (8192cu) or Ubuntu 14.04 (8192cu via https://github.com/pvaret/rtl8192cu-fixes)

I haven't been able to successfully setup multiple SSIDs using the patched version of hostapd. I was wondering if it's supported and if there are any additional steps I need to do?

I've been using http://wiki.stocksy.co.uk/wiki/Multiple_SSIDs_with_hostapd as reference, but obviously it's for the nl80211 driver so some of the steps we can not perform.

Any help would be greatly appreciated!

**Comment by pritambaral** [comment]
Blame Realtek. Their hacked up driver does not support mac80211 (which is what hostapd's nl80211 uses), and I'm not in favour of adding features to a hacked up driver.

I suggest you try to use the in-kernel driver (which might work with hostapd's nl80211 driver). The newer the kernel, the better the driver; I doubt 14.04 has a new enough kernel.
