### ISSUE TITLE
Incorporate Patch Disable Neighbor Scanning for 40MHZ

### ISSUE THREAD

**Issue by cannonfodder728** [pritambaral/hostapd-rtl871xdrv#18]
Can you incorporate the following patch to enable 40MHZ into your patch?

https://dev.openwrt.org/browser/trunk/package/network/services/hostapd/patches/300-noscan.patch

**Comment by pritambaral** [comment]
No, sorry. That patch does not belong in here. It belongs upstream, or in a general hostapd fork. This repo is not a general hostapd fork, and its purpose (hostapd support for shitty, proprietary rtl871x kernel drivers) is not served by that patch.
