### ISSUE TITLE
Building hostapd fails after applying patch

### ISSUE THREAD

**Issue by ShiplakeCS** [pritambaral/hostapd-rtl871xdrv#19]
I have been following these instructions to set up an AP using a Raspberry Pi, which includes applying this patch to hostapd.

However, after having applied the patch, when I attempt to rebuild hostapd make presents the following error:

```
pi@raspberrypi:~/wpa-2.3/hostapd $ make
  CC  main.c
  CC  config_file.c
  CC  ../src/ap/hostapd.c
  CC  ../src/ap/wpa_auth_glue.c
  CC  ../src/ap/drv_callbacks.c
  CC  ../src/ap/ap_drv_ops.c
  CC  ../src/ap/utils.c
  CC  ../src/ap/authsrv.c
  CC  ../src/ap/ieee802_1x.c
  CC  ../src/ap/ap_config.c
  CC  ../src/ap/eap_user_db.c
  CC  ../src/ap/ieee802_11_auth.c
  CC  ../src/ap/sta_info.c
  CC  ../src/ap/wpa_auth.c
  CC  ../src/ap/tkip_countermeasures.c
  CC  ../src/ap/ap_mlme.c
  CC  ../src/ap/wpa_auth_ie.c
  CC  ../src/ap/preauth_auth.c
  CC  ../src/ap/pmksa_cache_auth.c
  CC  ../src/ap/ieee802_11_shared.c
  CC  ../src/ap/beacon.c
../src/drivers/drivers.c:98:3: error: ‘wpa_driver_rtw_ops’ undeclared here (not in a function)
  &wpa_driver_rtw_ops,
   ^
Makefile:891: recipe for target '../src/drivers/drivers.o' failed
make: *** [../src/drivers/drivers.o] Error 1
```

I have looked inside drivers.c but am not sure how to proceed to fix the issue to allow the build to work properly.

Any advice?

Thanks!

**Comment by pritambaral** [comment]
Which version of hostapd are you applying this to, and which tag of this repo are you using?

**Comment by fr0zenrain** [comment]
@ShiplakeCS  2.2 with this error,i use 2.6 ok

**Comment by pritambaral** [comment]
Read the instructions; use the right patch with the right version.

**Comment by ghost** [comment]
Hi @pritambaral,

I am trying to build this on latest strech raspian and have when trying build after applying path it gives me following error.

> ../src/drivers/driver_rtw.c: In function ‘rtl871x_set_beacon_ops’:
> ../src/drivers/driver_rtw.c:1379:59: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘size_t {aka unsigned int}’ [-Wformat=]
>     printf("%s ssid_len(%u) != hapd->conf->ssid.ssid_len(%lu)!!\n", __func__
>                                                            ^
> ../src/drivers/driver_rtw.c:1389:45: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 5 has type ‘size_t {aka unsigned int}’ [-Wformat=]
>    printf("%s ignore_broadcast_ssid:%d, %s,%lu, expend_len:%u\n", __func__

Any help is appreciated,
Thanks in advance

**Comment by pritambaral** [comment]
@Fisherzz that's a warning, not an error. Do you even read?!
