### ISSUE TITLE
Patching error

### ISSUE THREAD

**Issue by Bob36180** [pritambaral/hostapd-rtl871xdrv#22]
I try to patch my hostapd 2.6 on Ubuntu 16.04 LTS but it shows me this error : 
```
root@bob-E202SA:/home/bob/hostapd-2.6# patch -Np1 -i rtlxdrv.patch
patching file hostapd/main.c
patching file src/ap/beacon.c
patching file src/ap/hw_features.c
patching file src/drivers/driver.h
patching file src/drivers/driver_bsd.c
patching file src/drivers/driver_rtl.h
patching file src/drivers/driver_rtw.c
patch: **** malformed patch at line 2431: 9+	//enter MASTER MODE when init.
```

Any ideas ?

**Comment by pritambaral** [comment]
Works fine for me.

Are you using the patch from the correct tag? How did you download the patch?

**Comment by Bob36180** [comment]
I've downloaded the patch in  'Clone or download' and 'Download ZIP' then I've unzipped the file and put it in the previous directory (/home/bob/hostapd-2.6)... I've just installed hostapd 2.6.

**Comment by pritambaral** [comment]
Could you tell what this says:

```sh
sha256sum rtlxdrv.patch
```

**Comment by Bob36180** [comment]
Yep !
```
root@bob-E202SA:/home/bob/hostapd-2.6# sha256sum rtlxdrv.patch
74b93a2ffac5d2692d7f47ed661dd3f7c58f63500b0f968f1211d00fc665969b  rtlxdrv.patch
```

**Comment by pritambaral** [comment]
Hmm, that doesn't match what I get here. Looks like your download is corrupted. The sha256sum of the patch for 2.6 should be `e204da659d0583c71af23cb9b55536fe99598ee26a44104344f456e4d17350c6`

**Comment by Bob36180** [comment]
'Kay, I re-downoad the file and we'll see...

**Comment by Bob36180** [comment]
Works !! It's better to download this patch using the command line 'sudo git clone ...'
Thanks for your help

**Comment by pritambaral** [comment]
Offtopic, but it's probably not a good idea to run git under root.

**Comment by Bob36180** [comment]
Yes, probably, but it works for me, so...
