### ISSUE TITLE
Hostapd error while using with TP link wn823N module

### ISSUE THREAD

**Issue by rohitsay89** [pritambaral/hostapd-rtl871xdrv#23]
Hi I did apply the patches to the fresh hostapd 2.6 downloaded from https://w1.fi/hostapd/. I am using beaglebone board to build and run the hostapd to create and access point with TPlink WN823N module. I get the following message when I run the compiled and patched version: 

```
root@beaglebone:/home/debian/rohit/hostapd-2.6/hostapd# ./hostapd -dd /etc/hostapd/hostapd.conf
random: Trying to read entropy from /dev/random
Configuration file: /etc/hostapd/hostapd.conf
drv->ifindex=7
l2_sock_recv==l2_sock_xmit=0x0x1403c88
ioctl[SIOCSIWMODE]: Invalid argument
Could not set interface to mode(3)!
Could not set interface to master mode!
rtl871xdrv driver initialization failed.
hostapd_interface_deinit_free(0x14036e0)
hostapd_interface_deinit_free: num_bss=1 conf->num_bss=1
hostapd_interface_deinit(0x14036e0)
wlan0: interface state UNINITIALIZED->DISABLED
hostapd_bss_deinit: deinit bss wlan0
wlan0: AP-DISABLED
hostapd_cleanup(hapd=0x1404298 (wlan0))
hostapd_free_hapd_data: Interface wlan0 wasn't started
hostapd_interface_deinit_free: driver=(nil) drv_priv=(nil) -> hapd_deinit
hostapd_interface_free(0x14036e0)
hostapd_interface_free: free hapd 0x1404298
hostapd_cleanup_iface(0x14036e0)
hostapd_cleanup_iface_partial(0x14036e0)
hostapd_cleanup_iface: free iface=0x14036e0

```
I want to understand at which point I am doing wrong. 
Thanks,
Rohit

**Comment by pritambaral** [comment]
1. Buy less shitty hardware;
2. Yell at the manufacturer for providing shitty software support for shitty hardware; finally
3. Read the README in full and figure out which kernel driver you are using — mainline (ideal) or shitty Realtek code propped up by the selfless work of people like [dz0ny](https://github.com/dz0ny/rt8192cu).

**Comment by rohitsay89** [comment]
Thanks for your reply, just wanted to know that by mainline you mean the one that TP-link provides on their website or the one with comes with the kernel. I am currently using 4.14 kernel on beaglebone black Rev C and using "https://eewiki.net/display/linuxonarm/BeagleBone+Black" to make and image and flash the emmc. It would be great if you can suggest any better hardware (Wifi Dongle) for using as an access point on beaglebone black.
Best,
Rohit

**Comment by pritambaral** [comment]
Mainline always means the latest released kernel from kernel.org.
