### ISSUE TITLE
Syntax error when executing patch-command

### ISSUE THREAD

**Issue by Exceen** [pritambaral/hostapd-rtl871xdrv#6]
I keep on getting the following error when executing the command 'patch -Np1 -i </home/pi/hostapd-rtlxdrv-master/rtlxdrv.patch>:

-bash: syntax error near unexpected token `newline`

The path is definitely the right one, I also tried executing the command as root. I got hostapd-2.4 from the website stated in the readme file.

Any ideas what's wrong?

**Comment by pritambaral** [comment]
You likely missed out the `/path/to/rtl871xdrv.patch` portion of that command.

And this is an issue tracker, not a support channel,
