### ISSUE TITLE
Mac adresse filter

### ISSUE THREAD

**Issue by Androsyn31** [pritambaral/hostapd-rtl871xdrv#8]
They lines in hostapd.conf is ignored by hostapd
macaddr_acl=1
accept_mac_file=/etc/hostapd/mac_accept

they don't work any issue?

**Comment by pritambaral** [comment]
##### :grey_exclamation: This is not an issue tracker for hostapd. This repo does not host hostapd. :grey_exclamation:

With that said, the patch provided in this repo does not touch anything that has anything to do with mac address filtering.
